version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.18  # Node.js image for deployment steps
    steps:
      - setup_remote_docker  # Enables Docker commands within CircleCI

      - run:
          name: Docker Hub Login
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Pull Docker Image
          command: docker pull kartavyatyagi/kattu:latest

      - run:
          name: Run Container
          command: |
            docker run -d -p 3000:3000 --name node-app kartavyatyagi/kattu:latest
      - run:
          name: Verify Container Status
          command: docker ps -a
workflows:
  deploy_workflow:
    jobs:
      - deploy