version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.18  # Node.js image for deployment steps
    steps:
      - setup_remote_docker  # Enables Docker commands within CircleCI

      - run:
          name: Pull Docker Image
          command: docker pull kartavyatyagi/kattu:latest

      - run:
          name: Run Container
          command: |
            docker run -d -p 3000:3000 --name node-app kartavyatyagi/kattu:latest

workflows:
  deploy_workflow:
    jobs:
      - deploy